services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  web1:
    restart: on-failure
    build: ./docker/web
    hostname: web1
    ports:
      - '81:5000'
  web2:
    restart: on-failure
    build: ./docker/web
    hostname: web2
    ports:
      - '82:5000'
  nginx:
    build: ./docker/nginx
    ports:
    - '80:80'
    depends_on:
    - web1
    - web2